#!/bin/bash

# Use this to run the b0 built from the repo

# Get dirname to current script
pushd `dirname $0` > /dev/null
ROOT=`pwd`
popd > /dev/null

__B0_DEV_DIR=$ROOT $ROOT/_build/src-b0/bzero.native "$@"
