#!/bin/bash

# Use this to run the b0 built from the repo

# Get dirname to current script
pushd `dirname $0` > /dev/null
ROOT=`pwd`
popd > /dev/null

__B0_DEV_DIR=$ROOT/_boot_b0/v/nop/b/ $ROOT/_boot_b0/v/nop/b/b0-exe/b0 "$@"
